### PR TITLE
Add DataStreamBidirectional API

### PR DESCRIPTION
**Pull request by corbin-phipps**
### Type

- [X] Bug fix
- [X] Feature addition
- [X] Feature update
- [ ] Documentation
- [ ] Build Infrastructure

### Side Effects

- [ ] Breaking change
- [ ] Non-functional change

### Goals

This PR adds the `DataStreamBidirectional` API and unit tests. Also fixes a race condition bug and adds handling of sequencing mismatches.

### Technical Details

* Added `DataStreamBidirectional` API to `NetRemoteDataStreamingService.proto`.
* Added server-side `DataStreamReaderWriter` implementation of the `ServerBidiReactor` gRPC reactor.
* Added client-side `DataStreamReaderWriter` implementation of the `ClientBidiReactor` gRPC reactor.
* Added two unit tests - one for fixed-type client streaming and one for continuous-type client streaming.
* Added handling for mismatched sequencing.
* Fixed a race condition bug affecting `DataStreamUpload`.

### Test Results

All tests pass.

### Reviewer Focus

None.

### Future Work

None.

### Checklist

- [X] Build target `all` compiles cleanly.
- [X] clang-format and clang-tidy deltas produced no new output.
- [X] Newly added functions include doxygen-style comment block.

### CODE REVIEW

**Comment by abeltrano** [comment]
> * Fixed a race condition bug affecting `DataStreamUpload`.

Was this the fix done in #207? If so, can we add a test we can add to ensure it's fixed and stays fixed?

**Review by abeltrano — CHANGES_REQUESTED** [review]
I added some comments/questions in #205 to address before we complete this.

**Comment by corbin-phipps** [comment]
> > * Fixed a race condition bug affecting `DataStreamUpload`.
> 
> Was this the fix done in #207? If so, can we add a test to ensure it's fixed and stays fixed?

Yes, the fix was in #207. The bug was found by the existing unit tests. I'm not sure how to specifically test this bug fix since it would likely do the same thing as the existing tests.

**Comment by corbin-phipps** [comment]
> I added some comments/questions in #205 to address before we complete this.

Thanks, will add the changes here

**Comment by abeltrano** [comment]
> > I added some comments/questions in #205 to address before we complete this.
> 
> Thanks, will add the changes here

Please make sure the change is merged back to the feature branch. Can probably cherry-pick it.

**Comment by abeltrano** [comment]
> > > * Fixed a race condition bug affecting `DataStreamUpload`.
> > 
> > 
> > Was this the fix done in #207? If so, can we add a test to ensure it's fixed and stays fixed?
> 
> Yes, the fix was in #207. The bug was found by the existing unit tests. I'm not sure how to specifically test this bug fix since it would likely do the same thing as the existing tests.

If the existing unit tests would find it consistently, then we're good.

**Review by abeltrano — APPROVED** [review]

**Pull request merged**
