### PR TITLE
Add DataStreamDownload API

### PR DESCRIPTION
**Pull request by corbin-phipps**
### Type

- [ ] Bug fix
- [X] Feature addition
- [X] Feature update
- [ ] Documentation
- [ ] Build Infrastructure

### Side Effects

- [ ] Breaking change
- [ ] Non-functional change

### Goals

This PR adds the `DataStreamDownload` API.

### Technical Details

* Added `DataStreamDownload` API to `NetRemoteDataStreamingService.proto` and associated types to `NetRemoteDataStream.proto`.
* Added API implementation to `NetRemoteDataStreamingService`.
* Added `DataStreamWriter` implementation of gRPC `ServerWriteReactor` reactor class to `NetRemoteDataStreamingReactors`.
* Added unit tests and client reactors to `TestNetRemoteDataStreamingServiceClient` and `TestNetRemoteDataStreamingReactors`.

### Test Results

All tests pass.

### Reviewer Focus

None.

### Future Work

None.

### Checklist

- [X] Build target `all` compiles cleanly.
- [X] clang-format and clang-tidy deltas produced no new output.
- [X] Newly added functions include doxygen-style comment block.

### CODE REVIEW

**Review by abeltrano — COMMENTED** [review]
This looks good, other than the Windows build failure. Can you take a look at that?
https://github.com/microsoft/netremote/actions/runs/8107181867/job/22158274829?pr=198

Also, there are some clang-tidy issues I'd like to get resolved before merging to develop. I'll send a PR to `feature/dataStreaming` with them, then we can integrate that here.

**Comment by corbin-phipps** [comment]
> This looks good, other than the Windows build failure. Can you take a look at that? https://github.com/microsoft/netremote/actions/runs/8107181867/job/22158274829?pr=198
> 
> Also, there are some clang-tidy issues I'd like to get resolved before merging to develop. I'll send a PR to `feature/dataStreaming` with them, then we can integrate that here.

Looks like `std::uniform_int_distribution` template can't use `uint8_t` or any 8-bit type

**Comment by abeltrano** [comment]
> Also, there are some clang-tidy issues I'd like to get resolved before merging to develop. I'll send a PR to `feature/dataStreaming` with them, then we can integrate that here.

#199

**Comment by abeltrano** [comment]
> > This looks good, other than the Windows build failure. Can you take a look at that? https://github.com/microsoft/netremote/actions/runs/8107181867/job/22158274829?pr=198
> > Also, there are some clang-tidy issues I'd like to get resolved before merging to develop. I'll send a PR to `feature/dataStreaming` with them, then we can integrate that here.
> 
> Looks like `std::uniform_int_distribution` template can't use `uint8_t` or any 8-bit type

Do we ever need single-bytes? In my experience, using `uint32_t` for random data generation is good enough since you can truncate it to a `uint8_t` if necessary (just pick a random byte from the `uint32_t`).

**Comment by corbin-phipps** [comment]
> > > This looks good, other than the Windows build failure. Can you take a look at that? https://github.com/microsoft/netremote/actions/runs/8107181867/job/22158274829?pr=198
> > > Also, there are some clang-tidy issues I'd like to get resolved before merging to develop. I'll send a PR to `feature/dataStreaming` with them, then we can integrate that here.
> > 
> > 
> > Looks like `std::uniform_int_distribution` template can't use `uint8_t` or any 8-bit type
> 
> Do we ever need single-bytes? In my experience, using `uint32_t` for random data generation is good enough since you can truncate it to a `uint8_t` if necessary (just pick a random byte from the `uint32_t`).

Since the data generated is a string, I was created one byte (char) at a time hence the use of `uint8_t`. In #200 I used `uint32_t` then casted to `uint8_t`

**Review by abeltrano — APPROVED** [review]

**Pull request merged**
